name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: cd boss && pipenv run mkdocs gh-deploy --force
